### ISSUE TITLE
Amount passed to NeoLine extensions changes badly when shown as the System Fee?

### ISSUE THREAD

**Issue by roschler** [NeoNEXT/neoline#105]
I am using the code below to ask the NeoLine N3 extension to send a transaction to the NEO blockchain:
```
return neo3Obj.invoke({
		scriptHash: gasTokenScriptHash,
		operation: 'transfer',
	args: [
			{
				// From - the user sending the transaction
				"type": "Address",
				"value" : thePickedaddress
			},
			{
				// To - the smart contract that should receive the payment.
				"type": "Hash160",
				"value": neochexScriptHash
			},
			{
				// Amount - the amount to send with the transaction
				"type": "Integer",
				"value": amountNeoGas.toString()
			},
			{
				// data[] object that the GasToken contract will pass
				//  to our smart contract's onNEP17Payment()
				//	public method.
				"type": "Array",
				"value": aryArgs
			},
		],
		fee: transactionFee.toString(),
		broadcastOverride: false,
		signers: [
			{
				account: neochexScriptHash,
				scopes: 1
			}
		],
	});
})
```

The amount of NEO GAS I am setting as the system fee is **2.653980069636211,** as you can see in the Chrome DevTools console:
```
amountNeoGas.toString()
"2.653980069636211"
```

However, when the NeoLine N3 extension pops up, the system fee is only **0.1004033**.  Why is this happening and how can it fix it if it is not a bug?

![image](https://user-images.githubusercontent.com/4660487/128573284-08a48ed9-907a-41f8-90e7-ca47624d1d2d.png)

**Comment by roschler** [comment]
My mistake.  I was confused when I didn't see the developer set payment amount on the `Details` tab and mistook the `System Fee`, the platform cost to process the transaction, as the developer set payment amount.  I'll open up a different issue requesting that the developer set payment amount also be shown on the `Details` tab along with the total of all 3 fees.

**Comment by hacfox** [comment]
I close it, open new one if any issues.
