### ISSUE TITLE
Show transaction payment amount and total on the Details tab?

### ISSUE THREAD

**Issue by roschler** [NeoNEXT/neoline#106]
Currently when the NeoLine extension pops up it shows the network base transaction fee and the cost of executing the transaction, also known as the system fee.  

![image](https://user-images.githubusercontent.com/4660487/128578113-d8049182-8643-4372-9e34-7f2a0c24beb6.png)

This means the user has to inspect a JSON object on the `Data` tab to discover the _transfer_ amount set by the developer.  This is awkward and makes it very hard for the user to get a quick glimpse of the total amount they are about to transfer when the hit the `Yes` button.

![image](https://user-images.githubusercontent.com/4660487/128578044-c8e6033d-72dd-441f-a12d-689c1eb23d81.png)

Instead, the extension should show the developer set transfer amount directly on the `Details` tab, and then show a total beneath all 3 figures.

Something like this:

```
GAS FEE: 0.0001
SYSTEM FEE: <Calculated by NeoLine via a invoke read-only call, as now>
PAYMENT AMOUNT: <Set by developer in the amountGas parameter>

TOTAL PAYMENT: <sum of above>
```

**Comment by hacfox** [comment]
Get the latest version and try, we have improved it several weeks ago.
