### ISSUE TITLE
Extension window isn't sized correctly on popup

### ISSUE THREAD

**Issue by roschler** [NeoNEXT/neoline#107]
When I invoke a transaction with the Chrome extension, it doesn't size itself to show all the fields.  As you can see in this graphic, you can't see the NETWORK FEE:

![image](https://user-images.githubusercontent.com/4660487/128847596-eb3b8fc5-67ef-438b-871c-9ca1fd7c340e.png)

If I resize the lower border with the mouse I see this:

![image](https://user-images.githubusercontent.com/4660487/128847656-d097bf37-6efb-49d0-a9ea-5e3394c00e60.png)

**Comment by hacfox** [comment]
Please check the latest version and try it again.
