### ISSUE TITLE
Support Sign Method for dapi

### ISSUE THREAD

**Issue by cloud8little** [NeoNEXT/neoline#108]
neo-node can sign a transaction, to support the Neo Name Service function, there is need for dapi to support the sign function too.

https://github.com/neo-project/neo-node/blob/963ccac2a1aee0a0afe78c2afe64609e917e084c/neo-cli/CLI/MainService.Wallet.cs#L467-L479

https://github.com/neo-project/neo/blob/af8483e1e21433f8444c2b7ebfdcb5f61e7885db/src/neo/Wallets/Wallet.cs#L632-L689

similar as the neonjs tx.sign function.

![629ca3aa23453573f874db70d527432](https://user-images.githubusercontent.com/34291844/141888687-600954e4-a7f8-4eac-ba3c-a60158c916a4.png)

**Comment by hacfox** [comment]
Already improved.
