### ISSUE TITLE
Add support to Ledger Hardware Wallets

### ISSUE THREAD

**Issue by gsmachado** [NeoNEXT/neoline#109]
It would really good if NeoLine supports Ledger Hardware Wallets.

**Comment by gsmachado** [comment]
@hactrox this is super needed. When is it coming?

**Comment by hacfox** [comment]
Already planned

**Comment by gsmachado** [comment]
> Already planned

When do you think it would be released? Any estimate?

**Comment by hacfox** [comment]
A thousand years at a glance. Yeah, we have supported it now 🎉🎉🎉.
