### ISSUE TITLE
"Address not found in" for Testnet invoke

### ISSUE THREAD

**Issue by ediopia** [NeoNEXT/neoline#110]
When we use "Address" type in "Array" of invoke script args, it returns an error.

<img width="1247" alt="Screen Shot 2021-12-08 at 6 05 46 PM" src="https://user-images.githubusercontent.com/6670368/145321161-31486bab-6fa8-4442-8240-cb525a5c279b.png">

**Comment by hacfox** [comment]
@ediopia Can you post the params here?
