### ISSUE TITLE
Display Public Key of the address

### ISSUE THREAD

**Issue by gsmachado** [NeoNEXT/neoline#112]
In the "Account Details" view, the user could click on a button to see the public key of that particular address (in an encoded format).

**Comment by hacfox** [comment]
I do not think the users need it, or any reasons for this? for the dapi devs, there is a description of how to [getPublicKey](https://neoline.io/dapi/N3.html#getPublicKey).

**Comment by gsmachado** [comment]
IMHO, no strong use case.

Just for convenience. If you could fit this somewhere in the details, by clicking a button or so, it would be nice. It's always good to get info about address/wallet when users or devs need it.

If you still think it's not required, you can close this issue.

**Comment by hacfox** [comment]
Yeah it will be added soon. I believe that users who really need it have no reason to refuse a simple&convenient function.

**Comment by hacfox** [comment]
@gsmachado Hi, you can see it through  `account details`.

**Comment by gsmachado** [comment]
@hacfox awesome! thanks!
