### ISSUE TITLE
Ugly display of long-named accounts in account-switching menu

### ISSUE THREAD

**Issue by csmuller** [NeoNEXT/neoline#117]
Accounts with long names are not displayed nicely in the account-switching menu of NeoLine.
For example, the account's name in the following image is displayed on multiple lines with a huge gap in-between.

![Screenshot 2022-06-09 at 12 39 34](https://user-images.githubusercontent.com/37138571/172828484-f582f295-4be4-4448-994b-22a8c9ddd40d.png)

Browser: Brave V1.39.111
NeoLine Version: 3.4.13
OS: macOS 12.4

**Comment by csmuller** [comment]
Hey @haiwulei, any idea on when you could tackle this issue?

**Comment by hacfox** [comment]
Hi @csmuller , We made some updates on v3.5.0, just update and enjoy.
