### ISSUE TITLE
[Feature Request] supporting witness rule as listed in NEP-21

### ISSUE THREAD

**Issue by overlordsecurity** [NeoNEXT/neoline#120]
details can be seen here https://github.com/neo-project/proposals/blob/dapi/nep-21.mediawiki

**Comment by hacfox** [comment]
@overlordsecurity Hi, We have supported witness rules now, you can get it [here] first(https://github.com/NeoNEXT/neoline/releases/tag/v3.6.1) if you want it, the online version is pending review now.
