### ISSUE TITLE
add `getNetworks` to n3 dapi

### ISSUE THREAD

**Issue by worlddeleteRin** [NeoNEXT/neoline#121]
We have `getNetworks` in `extension/dapi/index.ts`, but it's missing in `extension/dapi/neo3.ts`
So right now `getNetworks` method is injected into `window.NEOLine` but not in `window.NEOLineN3`, meanwhile it's documented as it should be there

**Comment by hacfox** [comment]
@worlddeleteRin Hello, We have improved it in v3.6.1, just waiting for the review now. if you need it now, you can get it [here](https://github.com/NeoNEXT/neoline/releases/tag/v3.6.1)
