### ISSUE TITLE
Support batch import and export of addresses with one password

### ISSUE THREAD

**Issue by superboyiii** [NeoNEXT/neoline#122]
Neoline has different passwords for different addresses, it's very inconvenient for address management and back up. Now many old users have multi addresses in one extension wallet, they want to export them all in one wallet with only one password as back-up. New users will also meet this issue when importing multi addresses from cli to neoline. I suggest supporting batch import and export, but have to consider about the compatibility.

**Comment by hacfox** [comment]
@superboyiii I agree with this. We've discussed this issue in the past, see #114. There's something we have to be very careful about the compatibility. Please be patient with us.
