### ISSUE TITLE
Feature request: Filter search

### ISSUE THREAD

**Issue by digimbyte** [NeoNEXT/neoline#123]
I have 1200+ NFT's in a wallet,
could we add a search filter in the top?
**PLEASE!** 
![image](https://user-images.githubusercontent.com/6645396/202404301-da5f34d0-2fa0-4adb-abe7-48b0ab8cccb7.png)

**Comment by hacfox** [comment]
@digimbyte Hi, as everyone knows you now own over 1200 NFTs 😆 🚀 . and this suggestion is good, we will update it later.
