### ISSUE TITLE
Can invoke 'transfer' method from GAS contract, but transaction does not deposit GAS to smart contract address?

### ISSUE THREAD

**Issue by robliou** [NeoNEXT/neoline#124]
Hi,

I'm trying to invoke the 'transfer' method of a NEO or GAS contract via Neoline, and the transaction appears to go invoke. However, the transaction does not appear as going through to the receiving smart contract address on TestNet?

Please see below for my code as well as some screenshots:

```const instance = new NEOLineN3.Init();

const transferAsset = instance.invoke({
        scriptHash: '0xd2a4cff31913016155e38e474a2c06d08be276cf',
        //This is the gas token contract scripthash: https://docs.neo.org/docs/en-us/reference/scapi/framework/native/Gas.html
        operation: 'transfer',
        args: [
            {
                type: "Address",
                value: "NW3eqonPrRueuWi85cpHgqDrRnxP8Xzyta",
            },
            {
                type: "Address",
                value: "NfA8V8aABWTcMHgxCUBStTPLHFisCyJnfu",
            },
            {
                type: "Integer",
                value: "2",
            },
            {
                type: "String",
                value: '5',
            }
        ],
        fee: '0.0001',
        broadcastOverride: false,
        signers: [
            {
                account: "0xb83c34adfaa1b364c79939142046b508d545256f",
                //The account is the scripthash of my wallet address!
                scopes: 16
                /* allowedContracts: ["0x6123f30d275130ac59a6e1a76b36775ab2b4a0c4", "0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5"],
                allowedGroups: [] */
            }
        ]
    })
```

Calling this module results in my NeoLine wallet displaying the following screen:

![image](https://user-images.githubusercontent.com/81087205/228502682-b20c8556-6dab-4bf2-b8dd-075f91480a70.png)

However, there is no specification on the amount of GAS being transferred? Also, when I click 'Yes', the transaction shows as executing successfully, however, when I check Testnet, even though the transaction is there, there is no actual deposit into the smart contract. 

![image](https://user-images.githubusercontent.com/81087205/228501975-47da45f5-b417-41dc-9465-071cf986cab1.png)

![image](https://user-images.githubusercontent.com/81087205/228503077-79375a33-b6cb-41b3-8856-15392c3f066c.png)

Any ideas what I'm doing wrong? I'm probably just missing a small detail somewhere, right?

谢谢，

**Comment by hacfox** [comment]
@robliou Hi, If you use the scopes: 16, you must have to set the `allowedContracts`, [more details](https://developers.neo.org/docs/n3/foundation/Transactions#scopes)
so there are two ways you can get what you want.
```
...
signers: [
            {
                account: "0xb83c34adfaa1b364c79939142046b508d545256f",
                //The account is the scripthash of my wallet address!
                scopes: 16,
               allowedContracts: ["0xd2a4cff31913016155e38e474a2c06d08be276cf"]
            }
        ]
...
```
or
```
...
signers: [
            {
                account: "0xb83c34adfaa1b364c79939142046b508d545256f",
                scopes: 1
            }
        ]
...
```

**Comment by robliou** [comment]
> 

Thank you, @hacfox . If I change the ``scopes`` to 1, then the contract goes through. However, I find that I cannot adjust the value of the GAS that is sent?

![image](https://user-images.githubusercontent.com/81087205/228522999-92155e9d-825e-4feb-be98-4024d45c2d8e.png)

Do you have any idea why this value circled in red (number of gas) is not being picked up? 

![image](https://user-images.githubusercontent.com/81087205/228523229-c9a26e71-d34f-4a74-9bd8-00187b78a87d.png)

Thanks,

**Comment by hacfox** [comment]
@robliou If you invoke your own contract, then the amount of gas depends on your contract implementation, if you invoke the GAS contract, then you only need to change the third args number, which is an integer value.
```
args: [
            {
                type: "Address",
                value: "NW3eqonPrRueuWi85cpHgqDrRnxP8Xzyta",
            },
            {
                type: "Address",
                value: "NfA8V8aABWTcMHgxCUBStTPLHFisCyJnfu",
            },
            {
                type: "Integer",
                // NW3... send 2e-8 GAS to NfA...(decimals: 8), change it to 200000000 if you want to send 2 GAS to NfA...
                value: "2", 
            },
            {
                type: "String",
                value: '5',
            }
        ],
```

**Comment by robliou** [comment]
@hacfox 

You are right- I did not set my decimals properly, so this explains why not value was showing up.

Will test retrieval of the ``data`` key:value pair in the morning.

Thank you, man!
