### ISSUE TITLE
Problems with id on switchWalletNetwork

### ISSUE THREAD

**Issue by vncoelho** [NeoNEXT/neoline#132]
I added a personalized network.
When I give `ID:0` it changes to this network.
Id 1 changes to mainenet of Neo 2
Id 2 changes to testnet of Neo 2
Id 3 changes to mainnet of Neo 3

How about testnet of Neo 3?

I think there should be a command to change the network based on a label, as well obtain all list possible networks.

**Comment by hacfox** [comment]
@vncoelho Hi, you can find the these IDs from [docs](https://neoline.io/dapi/N3.html#getNetworks-networkResult)
the ID: 6 changes to testnet of N3.
