### ISSUE TITLE
verifyMessage always returns false

### ISSUE THREAD

**Issue by melanke** [NeoNEXT/neoline#136]
I am having a strange behavior using `verifyMessage` with NeoLine. It's always returning `false` for signed messages **with salt**, even when copying the results of the [signMessage examples](https://neoline.io/signMessage/) it returns false with my wallet.

```js
    const resp = await neoline.signMessage({
        message: 'Hello World',
    })

    const resp2 = await neoline.verifyMessage(resp)

    console.log(resp2) // {result: false}
```

**Comment by haiwulei** [comment]
Here is our dAPI [documentation,]( https://neoline.io/dapi/N3.html#verifyMessage) please check the parameters.
![image](https://github.com/NeoNEXT/neoline/assets/23209610/75478feb-5647-450b-9777-18d3e9c63ab4)

**Comment by melanke** [comment]
You are right, thanks for your response, sorry for the confusion.
