### ISSUE TITLE
Create wallet password input

### ISSUE THREAD

**Issue by morrigan** [NeoNEXT/neoline#21]
View raw characters (unhide) in password field doesn't work.

When creating a wallet, a password is required to be inputed only once. This is an issue as a typo can be easily misplaced so a confirmation input would be nice.

**Comment by JiraiyaTheSage** [comment]
Also please add the ability to use complex passwords, not only numbers and letters. Thanks.

**Comment by hactrox** [comment]
@morrigan Hi, the issue was fixed already and the password will be required to input again for validation, enjoy!

**Comment by hactrox** [comment]
@Kakashi010 Reasonable suggestion. We have allowed complex passwords.
