### ISSUE TITLE
Discussion: Hardware Wallet Support

### ISSUE THREAD

**Issue by gsmachado** [NeoNEXT/neoline#22]
Are there any plans to support hardware wallets within NeoLine?

It would be really cool to support, for example, Ledger and Trezor. Then, NeoLine would be a bridge for those. Users could be able to connect a hardware wallet in NeoLine and then use it in dApps. 😄 

Maybe a dependency is that Ledger and Trezor need to support Neo N3 apps first, right?

**Comment by hactrox** [comment]
Thanks for your advice😄, yes the hardware wallet support feature is planned to add.
To achieve that, like you said, Ledger, Trezor or other hardware wallet need to support Neo N3 first.

**Comment by gsmachado** [comment]
> Thanks for your advice😄, yes the hardware wallet support feature is planned to add. To achieve that, like you said, Ledger, Trezor or other hardware wallet need to support Neo N3 first.

@hactrox @hacfox now Ledger has full support for Neo N3. When you guys will implement this integration on NeoLine? Thanks!

**Comment by gsmachado** [comment]
Let's keep discussing in #109
