### ISSUE TITLE
Event BLOCK_HEIGHT_CHANGED provides non-continuous blocks

### ISSUE THREAD

**Issue by gsmachado** [NeoNEXT/neoline#23]
I tried:

```javascript
const fn = (data) => {
       	console.log(data);
}
neoline.addEventListener(neoline.EVENT.BLOCK_HEIGHT_CHANGED, fn);
```

Check it out:

![image](https://user-images.githubusercontent.com/2124276/113068109-ef071f80-91bd-11eb-9f0f-e5a7f56a9b1a.png)

Block `5852492` is missing! And never arrived even after like 10 minutes observing.

It would be nice to provide a reliable and consistent interface to developers that they know all blocks would be provided (in a continuous manner).

FYI: I was using Neo N3 Testnet network.

**Comment by hacfox** [comment]
@gsmachado Hi, The missing block notification has been fixed, pull dev and check it plz!

**Comment by gsmachado** [comment]
I can confirm that this is fixed by what I could observe, testing in the Neo N3 Testnet. 💪
