### ISSUE TITLE
Question: Fetch network + chain

### ISSUE THREAD

**Issue by gsmachado** [NeoNEXT/neoline#24]
As a developer, how can I make sure that NeoLine's user account is currently at `TestNet` (network) and `Neo3` (chain)?

How can I get the information that it's `Neo3` instead of `Neo2`?

**Comment by gsmachado** [comment]
By testing the `dev` branch I could still not see the information coming whether it's Neo3 or Neo2.

**Comment by hacfox** [comment]
@gsmachado Hi, the latest N3 dAPI is pushed into dev, and the N3 Beta docs link is: [https://neoline.io/dapi/N3.html](url)

**Comment by gsmachado** [comment]
Yes, the last version of `dev` branch brings this info -- which is essential to dApps. I'm closing this issue. 💪
