### ISSUE TITLE
Remark is overwritten with "From NeoLine" 

### ISSUE THREAD

**Issue by melewetwo** [NeoNEXT/neoline#34]
According to the documentation it should be possible to add a remark that is written to the blockchain
![image](https://user-images.githubusercontent.com/7630602/114860205-fd734f00-9deb-11eb-8bfa-51352f57840e.png)

the remark is set here:
https://github.com/NeoNEXT/neoline/blob/bfebdda6b131bc74cc0bfc3ba172aeea8697cdc0/src/app/core/services/neon.service.ts

**Comment by hacfox** [comment]
Yes, right as you say that it shouldn't be overwritten, we will improve it in the next release. @melewetwo

**Comment by selimerunkut** [comment]
Thanks for the quick response @hacfox, when can we expect the next release, this functionality is pretty crucial for our dApp.

**Comment by hacfox** [comment]
@selimerunkut @melewetwo Hi, sorry for my late reply, we now have done the N3 dAPIs, and the remark has been added into dev branch, you can build the latest project which is on dev branch and test them. we decide to release this enhancement together with N3 dAPIs, It will not last long.
