### ISSUE TITLE
Wrong `network` value in returned blocks 

### ISSUE THREAD

**Issue by gsmachado** [NeoNEXT/neoline#47]
Even if the network is set to `N3TestNet` when `neolineN3.getNetworks()` is used, the blocks are returned with the `netWork` attribute set to `TestNet` instead of `N3TestNet`:

```json
{
    "chainId": 4,
    "netWork": "TestNet",
    "blockHeight": 233892,
    "blockTime": 1620305380768,
    "blockHash": "0xf7572a3344677ae80ab036fa90fc4fadd10c9088b258c1f9adcbaf9b88f20182",
    "tx": []
}
```

This can cause confusion for dApp developers and we should be consistent throughout the whole NeoLine library.

**Comment by hacfox** [comment]
@gsmachado Hi, `neolineN3.getNetworks()` should be removed, you need to use the common method `neoline.getNetworks()` instead. and also the `netWork` field that returns by event `BLOCK_HEIGHT_CHANGED` should be removed too. bc `chainId` makes a good distinction, `netWork` (here should be `network`) is redundant.
