### ISSUE TITLE
Inconsistent attribute names throughout the code

### ISSUE THREAD

**Issue by gsmachado** [NeoNEXT/neoline#48]
For example, there are objects where an attribute is called `netWork`, and in other objects, it's called `networks`. In this particular example, I would use `network` and `networks` (all lowercase, single word).

Another example is: in some objects the attribute name `ID` is used, and in other objects called `Id`, or `chainId`.

A complete consistency review should be done in the data models.

**Comment by hacfox** [comment]
@gsmachado We are handling this.

**Comment by hacfox** [comment]
Solved and close it. If any issues, feel free to create a new one.
