### ISSUE TITLE
Cannot query N3 wallet balance on TestNet using Chrome Extension

### ISSUE THREAD

**Issue by djnicholson** [NeoNEXT/neoline#51]
I have version 3.1.1 of the Chrome Extension installed

In the browser console I tried the following:
```
var n = new NEOLine.Init()
n.getBalance({"params":[{"address":"NajyfVej8DkRzS6cejjtuRsNV5UHidQFoj","contracts":["cf76e28bd0062c4a478ee35561011319f3cfa4d2"]}]}).then(console.log)
```

I get the following error: `{type: "RPC_ERROR", description: "An RPC error occured when submitting the request", data: null}`

`NajyfVej8DkRzS6cejjtuRsNV5UHidQFoj` is an address on N3 TestNet that has some TestNet GAS. `cf76e28bd0062c4a478ee35561011319f3cfa4d2` is the GAS contract on TestNet

**Comment by hacfox** [comment]
@djnicholson Hi, N3 dAPI version hasn't been released yet. if you are working on N3, you can checkout `dev` branch, and follow the N3 Beta dAPI docs [here](https://neoline.io/dapi/N3.html).

**Comment by djnicholson** [comment]
Thanks, that got me up and running.  When will a version with N3 support be available on the Chrome store?

For anyone else reading, I did:

```
git clone git@github.com:NeoNEXT/neoline.git
cd neoline
git checkout dev
npm install
npm run build
```

I then went to `chrome://extensions`, turned on `Developer mode` clicked `Load unpacked` and then pointed it at the `dist` folder in the `neoline` repo.

Running the following the Chrome console shows me my GAS balance as expected now:

```
GAS = "0x"+("cf76e28bd0062c4a478ee35561011319f3cfa4d2".match(/[a-fA-F0-9]{2}/g).reverse().join(''))
n = new NEOLineN3.Init()
n.getBalance({"params":[{"address":"NajyfVej8DkRzS6cejjtuRsNV5UHidQFoj","contracts":[GAS]}]}).then(console.log)
```

**Comment by hacfox** [comment]
@djnicholson Hi, first thank you for writing down your process here. We are currently covering some tests and preparing to write tutorial. If everything goes well, we will release it. I need to close it, if you have any problem, reopen or create a new one.
