### ISSUE TITLE
Cannot invoke an N3 contract

### ISSUE THREAD

**Issue by djnicholson** [NeoNEXT/neoline#52]
I am trying to invoke an N3 contract using the `invoke` method.  The NeoLine window opens but spins forever:

![image](https://user-images.githubusercontent.com/2515705/118337169-0d07b580-b4c8-11eb-82ef-5c6b7eab9cb6.png)

When I open the dev console (in the NeoLine window) I see an error:

![image](https://user-images.githubusercontent.com/2515705/118337488-c8304e80-b4c8-11eb-9b50-17c684b3b387.png)

This is my code that invokes the contract:

```
await neoLine.invoke({
      scriptHash: "0x11a57cc4da0c0020e8deb18092ed0b6c2e106b59",
      operation: "adoptPet",
      args: [{ type: "Integer", value: `${petId}` }],
      signers: [
        { account: base58.decode("NMTXqEGx5EarLKRHBNTDWgYSvTSWRXKqzH").toString("hex"), scopes: 1 },
      ],
    });
```

I also tried not specifying a signer (in case you just use the account open in the wallet):

```
await neoLine.invoke({
      scriptHash: "0x11a57cc4da0c0020e8deb18092ed0b6c2e106b59",
      operation: "adoptPet",
      args: [{ type: "Integer", value: `${petId}` }],
      signers: [],
    });
```

This time I see a different error:

![image](https://user-images.githubusercontent.com/2515705/118337688-29f0b880-b4c9-11eb-9ceb-47a648d1d3c5.png)

Note that the account I am trying to use (`NMTXqEGx5EarLKRHBNTDWgYSvTSWRXKqzH`) has 500 GAS.

**Comment by djnicholson** [comment]
I also tried the following code:

```
await neoLine.invoke({
      scriptHash: "0x11a57cc4da0c0020e8deb18092ed0b6c2e106b59",
      operation: "adoptPet",
      args: [{ type: "Integer", value: `${petId}` }],
      signers: [
        { account: bs58check.decode("NMTXqEGx5EarLKRHBNTDWgYSvTSWRXKqzH").toString("hex").substr(2), scopes: 1 },
      ],
    });
```

(I am properly Base58Check decoding the address and stripping the version byte so that the input is the correct length.)

But I still get this error:

![image](https://user-images.githubusercontent.com/2515705/118765973-ab7d7900-b830-11eb-86c3-27c4973d0458.png)

**Comment by hacfox** [comment]
@djnicholson Hi, `N3 RC1` has been expired, now the node version is `RC2`, so you got the error. It is recommended that you publish the contract on RC2 and do the test.

**Comment by hacfox** [comment]
@djnicholson Hey, now the node has been upgraded to `RC3`, and your `account` in `signers` should be `scripthash` of your address, and also you can see the code [here](https://github.com/NeoNEXT/neoline/blob/1a4c13c9c6341eca44e3aa784344ce2ee7f06d28/extension/common/utils.ts#L44). if any question of your `invoke`, just reopen or create a new one.
