### ISSUE TITLE
Add custom NEP-17 tokens

### ISSUE THREAD

**Issue by gsmachado** [NeoNEXT/neoline#58]
If this is already supported, it's not actually working in the current NeoLine version.

E.g., add a NEP-177 token that the balance would be displayed in the wallet. 😄

**Comment by hacfox** [comment]
Yeah, now it only supports NEO && GAS,  and will be supported soon.

**Comment by hacfox** [comment]
@gsmachado If you want to display assets and balances, first the contract you deploy must meet the standards for tokenized smart contracts, it need to include `[SupportedStandards("NEP17")]`, see [docs](https://docs.neo.org/docs/en-us/develop/write/nep17.html) or [github](https://github.com/neo-project/examples/blob/37487a324b4be695af422f37d668e15a05d75e1e/csharp/NEP17/NEP17.cs#L13).

**Comment by gsmachado** [comment]
Both NEP-17 and NEP-11 are supported now? Or just NEP-17?

**Comment by hacfox** [comment]
Now only supports NEP-17.

**Comment by gsmachado** [comment]
Thanks! Closing this now.
