### ISSUE TITLE
Add custom NEP-11 tokens

### ISSUE THREAD

**Issue by gsmachado** [NeoNEXT/neoline#68]
Add a NEP-11 token that the balance would be displayed in the wallet.

**Comment by hacfox** [comment]
@gsmachado We are handling it now.

**Comment by gsmachado** [comment]
@hacfox when will this be implemented? Is it in the roadmap? thanks!

**Comment by hacfox** [comment]
Hi, now you can add the NEP-11 in `NEP11`-> '+' -> `search` 
![image](https://user-images.githubusercontent.com/24224633/155447423-867e43aa-2ccb-4d95-8c81-f2fa6edccd42.png)

**Comment by gsmachado** [comment]
Great!
