### ISSUE TITLE
File Import password

### ISSUE THREAD

**Issue by ediopia** [NeoNEXT/neoline#70]
It validates password with its length check when I try to import wallet files.
Password length is not required in other wallets so users can not import if they've encrypted their wallet with shorter password length.

**Comment by hacfox** [comment]
@ediopia Yes, It must have to do the length check when import wallet files. We recommend to use a longer password rather than a shorter one.

**Comment by ediopia** [comment]
@hacfox I agree that secure password is always better however some wallets don't check the length when it creates a nep6 wallet for users including neo-cli.

**Comment by gsmachado** [comment]
My take: NeoLine could have an option/settings that would disable the enforcement of password length ONLY when importing wallets not generated by NeoLine.

What do you think about this, @hacfox ?

**Comment by hacfox** [comment]
@gsmachado @ediopia  Hi, we have released a new version `v3.3.0`, and contains this enhancement. you can disable the password check in `General settings`.
