### ISSUE TITLE
Communicate failed with wallet.

### ISSUE THREAD

**Issue by ioannistsil** [NeoNEXT/neoline#71]
Hi neoline  give error message  Communicate failed with wallet.  can you fix it

**Comment by hacfox** [comment]
How do you get this error?

**Comment by hacfox** [comment]
@ioannistsil I can’t judge what caused it. This error was reported on the other party’s website. You need to provide more specific information to analyze this.

**Comment by hacfox** [comment]
If any issues, feel free to create a new one.
