### ISSUE TITLE
ScriptHashToAddress is not a function

### ISSUE THREAD

**Issue by SimpleXTX** [NeoNEXT/neoline#75]
![image](https://user-images.githubusercontent.com/86066930/122424807-4c299a80-cf8f-11eb-94d5-9c99b92a6e69.png)

Unable to use the ScripHasToAddress which is stated here that it should be there: https://neoline.io/dapi/N3.html#scriptHashToAddress

**Comment by hacfox** [comment]
@SimpleXTX Hi, you should follow the docs, it should be called as `neolineN3.ScriptHashToAddress(...)`.

**Comment by SimpleXTX** [comment]
@hacfox Hello,

Sorry, but still does not work...

![image](https://user-images.githubusercontent.com/86066930/122432171-636b8680-cf95-11eb-9ddf-37008f1b2711.png)

**Comment by SimpleXTX** [comment]
![image](https://user-images.githubusercontent.com/86066930/122433245-54d19f00-cf96-11eb-8ca5-9d1ec78f06b3.png)

I can get the account, but ScriptHashToAddress does not exist

**Comment by hacfox** [comment]
@SimpleXTX have you pulled the latest `dev` branch? `master` is not supported yet. we will have a release in a few days.

**Comment by SimpleXTX** [comment]
@hacfox Hello, i just pulled the dev branch,
 ran npm install, 
and npm run build,
 but once i go to load unpackaged in chrome, it does not work, sais neoline.js does not exist, and i cant fid this file anywhere

![image](https://user-images.githubusercontent.com/86066930/122439046-96187d80-cf9b-11eb-82e5-25df90be853e.png)

**Comment by hacfox** [comment]
@SimpleXTX when you have built the project, it generates a `dist` folder, load `dist/` in chrome.

**Comment by SimpleXTX** [comment]
@hacfox 

Now i works, i had to downgrade my node version and install yarn, that did the trick

**Comment by hacfox** [comment]
@SimpleXTX ah, glad to hear that, so I will close it, and if any issues, just create a new one.
