### ISSUE TITLE
Write invoke method forever loads

### ISSUE THREAD

**Issue by SimpleXTX** [NeoNEXT/neoline#76]
![image](https://user-images.githubusercontent.com/86066930/122428928-a4ae6700-cf92-11eb-8aad-22b16c53a8f8.png)

This is the arguments i am passing in using the developer tools in chrome

NEOLineN3.N3.invoke({scriptHash: '0x6588d8bcb6c09f5a366a533a70b2c963f7f6fef9', operation: 'mintToken', args: [{"type":"ByteArray","value":"nHL4YwntxRhDBQMlHWwdxxd73htZllCYM5+FvzXLiWc="},{"type":"String","value":"{\"name\":\"A\"}"}], broadcastOverride: false, signers: [{account:"0xb9e8f559b070d41c8da0b99e86062acc818aacd7", scopes: "1"}]}).then(e => {console.log(e)})

**Comment by SimpleXTX** [comment]
![image](https://user-images.githubusercontent.com/86066930/122432337-8433dc00-cf95-11eb-9578-485d516a72a3.png)


That does not work...

neolineN3.invoke is not a function...

**Comment by hacfox** [comment]
Hi, the same as #75

**Comment by SimpleXTX** [comment]
@hacfox  you can close this as well, thanks
