### ISSUE TITLE
Error when building private_chain

### ISSUE THREAD

**Issue by MikeHibbert** [NeoNEXT/neoline#79]
Steps to recreate:

1) checkout branch
2) npm run initneonjs
3) npm install 
4) npm run build

Produces the error
```
ERROR in node_modules/@cityofzion/neon-js-neo3/lib/index.d.ts:3:96 - error TS2339: Property 'settings' does not exist on type 'typeof import("C:/Users/hibbe/Documents/Nodejs/neoline/node_modules/@cityofzion/neon-js-neo3/node_modules/@cityofzion/neon-core/lib/index")'.

3 declare const api: typeof import("@cityofzion/neon-api/lib/plugin"), settings: typeof neonCore.settings, sc: typeof neonCore.sc, rpc: typeof neonCore.rpc, wallet: typeof neonCore.wallet, CONST: typeof neonCore.CONST, u: typeof neonCore.u, tx: typeof neonCore.tx, logging: typeof neonCore.logging;
                                                                                                 ~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! neoline@3.2.1 build: `ng build --prod && yarn build:crx`
npm ERR! Exit status 1
```

**Comment by hacfox** [comment]
@MikeHibbert Hi, now you just try all steps again, it has been solved by upgrading package.

**Comment by MikeHibbert** [comment]
@hacfox Ok I ran the build steps again and got a little further but now its insisting an older version of Node: 

```
 neoline@3.2.1: The engine "node" is incompatible with this module. Expected version "^12.10.0". Got "14.2.0"
```

Is there any reason its set to the lower one?

**Comment by hacfox** [comment]
@MikeHibbert Yeah, It looks unreasonable this way, we will check and upgrade.  for now you can use nvm for version switching. Thanks for your report.

**Comment by MikeHibbert** [comment]
Ok, built successfully and installed but got errors when I enable it.

![neoline errors](https://user-images.githubusercontent.com/1153455/124581016-97c1bc80-de48-11eb-9fe8-8f2cd26ec296.png)

**Comment by hacfox** [comment]
@MikeHibbert we have improved it. check it out and try.

**Comment by MikeHibbert** [comment]
Ok! builds with no errors after install!

@hacfox So even though it says testnet it it really means local?

**Comment by hacfox** [comment]
@MikeHibbert Yes, you're right, and we are doing some fixes on `private_chain`, just wait for a while. it will be pushed today.

**Comment by hacfox** [comment]
@MikeHibbert  Please follow the [README.md](https://github.com/NeoNEXT/neoline/blob/private_chain/README.md), especially step 2.

**Comment by MikeHibbert** [comment]
@hacfox Ok so I followed the new instructions and set the neo3TestRPC to 'neo3TestRPC: 'http://127.0.0.1:50012' for my neo express instance and set 
```
export const NEO3_MAGIC_NUMBER_TESTNET = 2567014327; // 844378958;
```

I built the project and imported the plug and added an existing wallet but I can not see any balance of NEO or GAS and I'm certain there is at least 100 NEO and 999 GAS in there

**Comment by hacfox** [comment]
@MikeHibbert  you should check the node yourself, or you can do a RPC request  to see if it works.

**Comment by hacfox** [comment]
@MikeHibbert Hey, Does it work now? `ERROR TypeError: Cannot read property 'balance' of undefined` has been fixed.
