### ISSUE TITLE
Typo in documentation - "ensures allow compatibility"

### ISSUE THREAD

**Issue by roschler** [NeoNEXT/neoline#84]
On this page in the documentation:

https://neoline.io/dapi/N3.html#signMessage

You have this paragraph:

"Signs a provided messaged with an account selected by user. A randomized salt prefix is added to the input string before it is signed, and it is encased in a non-executable transaction before signed. This ensures allow compatibility with Ledger devices."

I believe you want to delete "allow":

"ensures compatibility"

**Comment by hacfox** [comment]
@roschler improved!
