### ISSUE TITLE
NeoLineN3 extension does not detect network unavailability

### ISSUE THREAD

**Issue by roschler** [NeoNEXT/neoline#85]
I sent a transaction with the NeoLineN3 extension when my local NEO Express instance was not running.  I saw these messages in the  Chrome DevTools console:
```
NeoLine configured.
neolineN3.js:43 NeoLineN3 configured.
neoline-n3-test.html:196 NEOLineN3 ready event received.
neoline-n3-test.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
neoline-n3-test.html:159 Invoke transaction success!
```

You can see the error about the port being closed, but then the message that the transaction was a success.  Also, the extension does not give any indication that there was a problem with the transaction.  The extension should detect the port error and suggest to the user that the blockchain network or RPC node is down or currently unavailable.

**Comment by hacfox** [comment]
@roschler Now you can ignore this log, it does not affect any functionality, we will improve it later.
