### ISSUE TITLE
NeoLineN3 extension complains about a missing "Verify()" method.  Also, typo in error message.

### ISSUE THREAD

**Issue by roschler** [NeoNEXT/neoline#86]
I tried to use the `NeoLineN3` "invoke" method to call a method in my smart contract.  I saw the following error in the Chrome DevTools console:
```
  ✓ Transaction created 
main-es2015.759cd50fdb1024b232bf.js:1   ✓ Network Fee set: 0.01201 
main-es2015.759cd50fdb1024b232bf.js:1 Error: The smart contract 0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5 haven't got verify method.
    at W.execute (main-es2015.759cd50fdb1024b232bf.js:1)
    at async W.invokeContractVerify (main-es2015.759cd50fdb1024b232bf.js:1)
main-es2015.759cd50fdb1024b232bf.js:1 {type: "rpcError", error: {…}}
```
Should I add a "verify()" method to my smart contract and if so, what should it do?  I never needed a method like this when doing "Invoke" operations from a `neon-js` invoke call.  I saw this page on your site:

https://neoline.io/dapi/N3.html#verifyMessage

But that doesn't seem to tell me what the code for my "verify" method should look like and what arguments I should declare that message with.

Also, look at the error message.  It says:

```
"haven't got verify method"
```

It should be "verify method missing" or "don't have a verify method".

**Comment by roschler** [comment]
UPDATE: This error appears to occur when you have the wrong script hash.  I had done a re-deploy and not updated the smart contract script hash in my NeoLineN3 code.  Now that I have done that, I am not getting the error.  Perhaps a better error message would be helpful, one that indicates that the smart contract hash might be wrong?

**Comment by hacfox** [comment]
@roschler If the contract doesn't have `verify` method, we will set a default value for it. This is just a log output. will improve.
