### ISSUE TITLE
Not seeing notifications for BLOCK_HEIGHT_CHANGED

### ISSUE THREAD

**Issue by jastez** [NeoNEXT/neoline#88]
We see this in common:

```
export enum EVENT {
    READY = 'NEOLine.N3.EVENT.READY',
}
```

Are we missing Events for N3?

**Comment by jastez** [comment]
Also, we are using TestNet N3

**Comment by hacfox** [comment]
Hey, if you want to listen the events for Neo2 and N3 `BLOCK_HEIGHT_CHANGED`, you need to init a NEOLine(Neo2) instance. we put the common listeners together, and should be called by `NEOLine(Neo2)` instance but not `NEOLineN3`

**Comment by jastez** [comment]
@hacfox Do you think you can update the docs for both N2 and N3 a bit? It seems in N3 docs there is mention that listening to events should work. So if we need the N2 object for this behavior, it would help us out a lot. Also any other doc updates would be huge for us.

**Comment by hacfox** [comment]
@jastez Yeah, we are handling it now. The docs will be updated soon.

**Comment by hacfox** [comment]
If any issues, feel free to create a new one.
