### ISSUE TITLE
Catch block in documentation samples needs updating, bad "catch" block. 

### ISSUE THREAD

**Issue by roschler** [NeoNEXT/neoline#89]
The `catch` block in the method samples on the NeoLine N3 documentation site is as follows:
```
.catch(({type, description, data}) => {
    switch(type) {
        case 'NO_PROVIDER':
            console.log('No provider available.');
            break;
        case 'CONNECTION_REFUSED':
            console.log('Connection dApp not connected. Please call the "connect" function.');
            break;
        case 'RPC_ERROR':
                console.log('There was an error when broadcasting this transaction to the network.');
                break;
    }
});
```

The problem with having the `catch` block declared like that is if the error is not one you expected to catch that `catch` block fails to report anything because the variable `type` is undefined and none of the `switch` statement branches execute, resulting in no error output.  In other words if the object received by the `catch` block is not an object with 3 fields, no errors are reported because `type` is **undefined**.  If your code throws a single field error object, the switch statement does not work properly.

I changed the `catch` block to this.  Note the addition of the `default` clause too:
```
.catch(err => {
    const {type, description, data} = err;
    switch(type) {
        case 'NO_PROVIDER':
            console.error('No provider available.');
            break;
        case 'CONNECTION_REFUSED':
            console.error('Connection dApp not connected. Please call the "connect" function.');
            break;
        case 'RPC_ERROR':
                console.error('There was an error when broadcasting this transaction to the network.');
                break;
        default:
            // Not an expected error object.  Just write the error to the console.
            console.error(err);
            break;
    }
})
```

The instant I did that I started seeing this error:
```
neoline-n3-test.html:266 DOMException: Failed to execute 'postMessage' on 'Window': #<Promise> could not be cloned.
    at chrome-extension://lndmeehkleglfaigokdnpoojklbhnggo/dapiN3.js:43:698406
    at new Promise (<anonymous>)
    at c (chrome-extension://lndmeehkleglfaigokdnpoojklbhnggo/dapiN3.js:43:698320)
    at e.invokeRead (chrome-extension://lndmeehkleglfaigokdnpoojklbhnggo/dapiN3.js:43:702873)
    at testNeolineN3_sc_buy_option (http://127.0.0.1:5500/neoline-n3-test.html:182:14)
```

And in the NeoLineN3 background panel for the extension:
```
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
```

Screenshot:

![image](https://user-images.githubusercontent.com/4660487/125234301-6ca6f500-e2ae-11eb-8c50-d2c36991a860.png)

**Comment by hacfox** [comment]
@roschler it should be coded end with default, we will improve it soon.

**Comment by hacfox** [comment]
@roschler improved! check the docs.

**Comment by hacfox** [comment]
Solved and close it.
