### ISSUE TITLE
DOMException: Failed to execute 'postMessage' on 'Window': #<Promise> could not be cloned.

### ISSUE THREAD

**Issue by roschler** [NeoNEXT/neoline#90]
When I try to execute the `invoke` or `invokeRead` method the extension does not pop up and I see the following error in the console log, _after_ I changed my `catch` block for the `invoke/invokeRead` call, as I stated in this other issue I reported:

https://github.com/NeoNEXT/neoline/issues/89

```
neoline-n3-test.html:266 DOMException: Failed to execute 'postMessage' on 'Window': #<Promise> could not be cloned.
    at chrome-extension://lndmeehkleglfaigokdnpoojklbhnggo/dapiN3.js:43:698406
    at new Promise (<anonymous>)
    at c (chrome-extension://lndmeehkleglfaigokdnpoojklbhnggo/dapiN3.js:43:698320)
    at e.invokeRead (chrome-extension://lndmeehkleglfaigokdnpoojklbhnggo/dapiN3.js:43:702873)
    at testNeolineN3_sc_buy_option (http://127.0.0.1:5500/neoline-n3-test.html:182:14)
```

And in the NeoLineN3 background panel for the extension:
```
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
```

Unfortunately I can not do `invoke/invokeRead` calls using the NeoLineN3 plugin at this point and therefore my dApp development is on hold because of this.  I am looking forward to your reply when you can take a look at this.

Screenshot:

![image](https://user-images.githubusercontent.com/4660487/125234301-6ca6f500-e2ae-11eb-8c50-d2c36991a860.png)

**Comment by hacfox** [comment]
@roschler the `invokeread` will not pop up a screen for you, and you just need to ignore the error: `Unchecked runtime.lastError`, it does not affect the extension.

**Comment by roschler** [comment]
"@roschler the invokeread doesn't pop up a screen for you"

Yes that's the problem.  How do I fix it?

**Comment by hacfox** [comment]
It's not a problem. If you do the `invokeread`, It's just the same as doing a RPC request. You'll get the response straightly.
