### ISSUE TITLE
When using the "Send“ call to send more Gas than you actually have in your wallet

### ISSUE THREAD

**Issue by flashrob01** [NeoNEXT/neoline#93]
When using the "neolineN3.send" call to send gas to a sample address, I noticed that if you don't have enough gas in your wallet, you will either receive an unrelated console error message: "  ("Unchecked runtime.lastError: The message port closed before a response was received.")." or no error message at all. 

Instead, a clear error message should be returned in the Neoline user's interface to retry by sending less than your max Gas balance... 👍

**Comment by hacfox** [comment]
@flashrob01 It has been solved.#94

**Comment by flashrob01** [comment]
> @flashrob01 It has been solved.#94

Thanks Hacfox. 

By the way- as a follow-up question. 

When using that send method; how do we use the getAccount method to automatically send our address from our wallet to that send method? The getAccount method I'm referring to is:

"neoline.getAccount()
.then(account => {
    const {
        address,
        label
    } = account;

    console.log('Provider address: ' + address);
    console.log('Provider account label (Optional): ' + label);
})"

**Comment by hacfox** [comment]
I know you got a right answer yourself now, open a new one if any issues.
